import { promises as fs } from 'node:fs';
import path from 'node:path';

import {
  LOCALHOST_CHAIN_ID,
  LOCALHOST_DEPLOYMENT_PATH,
  LOCALHOST_NETWORK_NAME,
  type LocalhostDeployment,
} from './helpers/deployments.js';

type Artifact = { abi: unknown };
type AbiEntry = {
  type?: string;
  name?: string;
};
type AbiSelection = {
  errors?: readonly string[];
  events?: readonly string[];
  functions?: readonly string[];
};
type AbiSource = {
  exportName: 'MockUSDCAbi' | 'PolicyVaultAbi';
  artifactPath: string;
  selection?: AbiSelection;
};

const ROOT = process.cwd();
const GENERATED_DIR = path.join(ROOT, 'app', 'src', 'lib', 'generated');
const ABI_OUTPUT_PATH = path.join(GENERATED_DIR, 'abi.ts');
const ADDRESS_OUTPUT_PATH = path.join(GENERATED_DIR, 'addresses.ts');
const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000';
const ABI_SOURCES: readonly AbiSource[] = [
  {
    exportName: 'MockUSDCAbi',
    artifactPath: path.join(ROOT, 'artifacts', 'contracts', 'MockUSDC.sol', 'MockUSDC.json'),
    selection: {
      errors: [
        'ERC20InsufficientAllowance',
        'ERC20InsufficientBalance',
        'ERC20InvalidApprover',
        'ERC20InvalidReceiver',
        'ERC20InvalidSender',
        'ERC20InvalidSpender',
        'ERC2612ExpiredSignature',
        'ERC2612InvalidSigner',
        'InvalidAccountNonce',
      ],
      events: ['Approval', 'Transfer'],
      functions: ['allowance', 'approve', 'balanceOf', 'decimals', 'name', 'nonces', 'permit', 'symbol'],
    },
  },
  {
    exportName: 'PolicyVaultAbi',
    artifactPath: path.join(
      ROOT,
      'artifacts',
      'contracts',
      'interfaces',
      'IPolicyVault.sol',
      'IPolicyVault.json',
    ),
  },
];

async function readAbi(artifactPath: string): Promise<unknown | undefined> {
  try {
    const raw = await fs.readFile(artifactPath, 'utf8');
    const artifact = JSON.parse(raw) as Artifact;
    return artifact.abi;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return undefined;
    }

    throw error;
  }
}

async function readLocalhostDeploymentOrUndefined(): Promise<LocalhostDeployment | undefined> {
  try {
    const raw = await fs.readFile(LOCALHOST_DEPLOYMENT_PATH, 'utf8');
    const deployment = JSON.parse(raw) as LocalhostDeployment;

    if (deployment.network !== LOCALHOST_NETWORK_NAME) {
      throw new Error(
        `Expected deployment network "${LOCALHOST_NETWORK_NAME}", received "${deployment.network}" in ${LOCALHOST_DEPLOYMENT_PATH}.`,
      );
    }

    return deployment;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return undefined;
    }

    throw error;
  }
}

function selectAbiEntries(abi: unknown, selection: AbiSelection | undefined): unknown {
  if (!Array.isArray(abi) || selection === undefined) {
    return abi;
  }

  const allowedNamesByType = {
    error: new Set(selection.errors ?? []),
    event: new Set(selection.events ?? []),
    function: new Set(selection.functions ?? []),
  } as const;

  return (abi as AbiEntry[]).filter((entry) => {
    if (!entry || typeof entry !== 'object' || typeof entry.type !== 'string') {
      return false;
    }

    if (!Object.hasOwn(allowedNamesByType, entry.type)) {
      return false;
    }

    return allowedNamesByType[entry.type as keyof typeof allowedNamesByType].has(entry.name ?? '');
  });
}

function renderAbiFile(
  entries: readonly {
    exportName: AbiSource['exportName'];
    abi: unknown | undefined;
  }[],
): string {
  const missingArtifacts = entries
    .filter((entry) => entry.abi === undefined)
    .map((entry) => entry.exportName.replace(/Abi$/, ''));
  const warningComment =
    missingArtifacts.length === 0
      ? ''
      : `// WARNING: Missing artifact ABI for ${missingArtifacts.join(', ')}. Run \`pnpm compile\` and \`pnpm abi:sync\` to populate real ABIs.\n`;

  const body = entries
    .map(
      (entry) =>
        `export const ${entry.exportName} = ${JSON.stringify(entry.abi ?? [], null, 2)} as const;`,
    )
    .join('\n\n');

  return `// Auto-generated by scripts/sync-abi.ts. Do not edit by hand.\n${warningComment}\n${body}\n`;
}

function renderAddressesFile(deployment: LocalhostDeployment | undefined): string {
  const localhostAddresses = deployment
    ? {
        chainId: deployment.chainId,
        mockUsdc: deployment.mockUsdc,
        policyVault: deployment.policyVault,
      }
    : {
        chainId: LOCALHOST_CHAIN_ID,
        mockUsdc: ZERO_ADDRESS,
        policyVault: ZERO_ADDRESS,
      };
  const warningComment = deployment
    ? `// Source: ${path.relative(ROOT, LOCALHOST_DEPLOYMENT_PATH)}\n`
    : `// WARNING: Missing ${path.relative(ROOT, LOCALHOST_DEPLOYMENT_PATH)}. Run \`pnpm deploy:local\` and \`pnpm abi:sync\` to populate real localhost addresses.\n`;

  return `// Auto-generated by scripts/sync-abi.ts. Do not edit by hand.\n${warningComment}\nexport const generatedAddresses = {\n  localhost: {\n    chainId: ${localhostAddresses.chainId},\n    mockUsdc: '${localhostAddresses.mockUsdc}' as \`0x\${string}\`,\n    policyVault: '${localhostAddresses.policyVault}' as \`0x\${string}\`,\n  },\n} as const;\n\nexport const hasGeneratedLocalhostAddresses = ${deployment !== undefined};\n`;
}

async function main(): Promise<void> {
  await fs.mkdir(GENERATED_DIR, { recursive: true });

  const abiEntries: {
    exportName: AbiSource['exportName'];
    abi: unknown | undefined;
  }[] = [];
  for (const source of ABI_SOURCES) {
    const abi = await readAbi(source.artifactPath);
    if (abi === undefined) {
      console.warn(`Missing ABI artifact for ${source.exportName} at ${source.artifactPath}`);
    }

    abiEntries.push({
      exportName: source.exportName,
      abi: selectAbiEntries(abi, source.selection),
    });
  }

  const deployment = await readLocalhostDeploymentOrUndefined();
  if (deployment === undefined) {
    console.warn(
      `Missing localhost deployment at ${LOCALHOST_DEPLOYMENT_PATH}; generating placeholder app/src/lib/generated/addresses.ts`,
    );
  }

  await fs.writeFile(ABI_OUTPUT_PATH, renderAbiFile(abiEntries), 'utf8');
  await fs.writeFile(ADDRESS_OUTPUT_PATH, renderAddressesFile(deployment), 'utf8');

  console.log(`Wrote ABI file to ${ABI_OUTPUT_PATH}`);
  console.log(`Wrote address file to ${ADDRESS_OUTPUT_PATH}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
