import { promises as fs } from 'node:fs';
import path from 'node:path';

type Artifact = { abi: unknown };

const ROOT = process.cwd();
const GENERATED_DIR = path.join(ROOT, 'app', 'src', 'lib', 'generated');
const SOURCES = [
  {
    name: 'MockUSDC',
    artifactPath: path.join(ROOT, 'artifacts', 'contracts', 'MockUSDC.sol', 'MockUSDC.json'),
  },
  {
    name: 'PolicyVault',
    artifactPath: path.join(ROOT, 'artifacts', 'contracts', 'PolicyVault.sol', 'PolicyVault.json'),
  },
];

async function readAbi(artifactPath: string): Promise<unknown> {
  const raw = await fs.readFile(artifactPath, 'utf8');
  const artifact = JSON.parse(raw) as Artifact;
  return artifact.abi;
}

async function main(): Promise<void> {
  await fs.mkdir(GENERATED_DIR, { recursive: true });

  const entries: string[] = [];
  for (const source of SOURCES) {
    try {
      const abi = await readAbi(source.artifactPath);
      entries.push(`export const ${source.name}Abi = ${JSON.stringify(abi, null, 2)} as const;`);
    } catch {
      console.warn(`Skipping ${source.name}: artifact not found at ${source.artifactPath}`);
    }
  }

  const output =
    entries.length > 0
      ? `// Auto-generated by scripts/sync-abi.ts\n\n${entries.join('\n\n')}\n`
      : `// No ABIs generated yet. Run 'pnpm compile' first.\nexport const MockUSDCAbi = [] as const;\nexport const PolicyVaultAbi = [] as const;\n`;

  await fs.writeFile(path.join(GENERATED_DIR, 'abi.ts'), output, 'utf8');
  console.log(`Wrote ABI file to ${path.join(GENERATED_DIR, 'abi.ts')}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
